apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - protocol: TCP
      port: 80       # service port
      targetPort: 4499 # container port
      nodePort: 30080  # external access in Minikube/Kind

